apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-app-cluster
  region: us-west-1
  version: "1.31"

iam:
  withOIDC: true

vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single

managedNodeGroups:
  - name: demo-app-ng-1
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 20
    volumeType: gp3
    privateNetworking: true
    ssh:
      allow: false
    labels:
      role: worker
      environment: production
    tags:
      nodegroup-role: worker
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/demo-app-cluster: "owned"
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        ebs: true
        albIngress: true
        cloudWatch: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
