"""Post-mortem node: Draft incident report."""

from datetime import datetime
from agent.state import AgentState, PostMortem


def post_mortem_node(state: AgentState) -> AgentState:
    """Generate comprehensive incident post-mortem report.

    Includes:
    - Timeline of events
    - Root cause analysis
    - Contributing factors
    - Remediation actions taken
    - Action items for prevention
    - Full markdown report

    Args:
        state: Current agent state with complete incident data

    Returns:
        Updated state with post-mortem report
    """
    print("📝 POST-MORTEM: Drafting incident report...")

    # TODO: Implement actual post-mortem generation using LLM
    # - Build timeline from messages and tool_calls
    # - Extract root cause from confirmed hypothesis
    # - Identify contributing factors
    # - Document remediation taken
    # - Generate actionable prevention items
    # - Format as markdown

    # Calculate incident duration
    started_at = state.get("started_at")
    completed_at = state.get("completed_at") or datetime.now()

    if started_at:
        duration_minutes = (completed_at - started_at).total_seconds() / 60
    else:
        duration_minutes = 0.0

    # Extract root cause from verification results
    root_cause = "Unknown"
    verification_results = state.get("verification_results", [])
    for result in reversed(verification_results):
        if result["status"] == "confirmed":
            root_cause = result["hypothesis"]["description"]
            break

    # Build timeline
    timeline = []
    for msg in state.get("messages", []):
        timeline.append({
            "timestamp": completed_at,  # Would use actual message timestamps
            "event": msg.get("content", "")
        })

    # Extract remediation
    recovery_proposal = state.get("recovery_proposal")
    execution_result = state.get("execution_result")

    if execution_result and execution_result["success"]:
        remediation_taken = recovery_proposal["description"] if recovery_proposal else "Unknown"
    else:
        remediation_taken = "No remediation executed" + (
            f" - {state.get('escalation_reason')}" if state.get("escalation_reason") else ""
        )

    # Generate markdown report
    incident = state.get("incident")
    service_name = incident["service"] if incident else "Unknown Service"
    alert_id = incident["alert_id"] if incident else "Unknown"

    markdown_report = f"""# Incident Post-Mortem: {service_name}

**Alert ID:** {alert_id}
**Date:** {completed_at.strftime('%Y-%m-%d %H:%M:%S')}
**Duration:** {duration_minutes:.1f} minutes
**Status:** {state.get('status')}

## Summary

An incident affecting {service_name} was detected and investigated.

## Timeline

{chr(10).join(f"- {event['event']}" for event in timeline[:10])}

## Root Cause

{root_cause}

## Contributing Factors

- Placeholder contributing factor 1
- Placeholder contributing factor 2

## Remediation

{remediation_taken}

## Action Items

- [ ] Placeholder action item 1
- [ ] Placeholder action item 2
- [ ] Review and improve monitoring for this scenario

---
*Generated by AI Incident Response Engineer*
"""

    post_mortem: PostMortem = {
        "timeline": timeline,
        "root_cause": root_cause,
        "contributing_factors": ["Placeholder factor 1", "Placeholder factor 2"],
        "remediation_taken": remediation_taken,
        "action_items": ["Placeholder action item 1", "Placeholder action item 2"],
        "incident_duration": duration_minutes,
        "report_markdown": markdown_report
    }

    print(f"   📊 Incident duration: {duration_minutes:.1f} minutes")
    print(f"   🎯 Root cause: {root_cause}")
    print("   ✅ Post-mortem complete")

    # TODO: Post to Slack and save as markdown file

    return {
        **state,
        "post_mortem": post_mortem,
        "completed_at": completed_at,
        "messages": state.get("messages", []) + [
            {"role": "system", "content": "Post-mortem generated"}
        ]
    }
